### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by johankvint** [bentatum/better-react-spinkit#10]
Not working as expected when using SSR.
```
Warning: React attempted to reuse markup in a container but the checksum was invalid. 
This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. 
React injected new markup to compensate which works but you have lost many of the benefits of server rendering. 
Instead, figure out why the markup being generated is different on the client or server:
 (client)  brsk-fading-circle-f2df12b1-287e-4b35-9
 (server)  brsk-fading-circle-7a1c6164-7f89-4b1d-a
```
Seams the animation name gets generated again at client side.
Is this something you could fix or is it to much of a rewrite?

**Comment by bentatum** [comment]
I'm not sure I have a solution for this. If you have ideas, feel free to send a PR my way.

Sorry about that and thanks for the heads up.

**Comment by FabricioPavano** [comment]
Same happens to me, doesn't break but it's kind of annoying, anything i can do to remove this Warning?

**Comment by FabricioPavano** [comment]
nevermind the issue is not related to this library. thanks for your work!

**Comment by aequasi** [comment]
Issue is related to this library. It does leave a warning in the console, and may affect SEO/GoogleBot, as they might see it as cloaking.

**Comment by jarib** [comment]
I'm also seeing this issue. What makes you think it's not related to this library, @FabricioPavano?

**Comment by bentatum** [comment]
I'll remove the dynamic name generation. That should fix it.

**Comment by slifszyc** [comment]
I've opened a PR to fix this
