### ISSUE TITLE
Slight delay on render 

### ISSUE THREAD

**Issue by bradabelgit** [bentatum/better-react-spinkit#2]
Awesome job on this :D Although, there seems to be a 0.5-1 second delay before the spinner actually shows up. I noticed this on the docs site. Is this due to a default fade in? If so, it would be nice to determine the duration of fade-in, or no fade in at all.

**Comment by bentatum** [comment]
Thanks for pointing this out @bradabelgit. The spinner has a `fadeIn` property. Setting it to `false` will remove the fade effect.

**Comment by bradabelgit** [comment]
@bentatum Derp on my part, thanks so much, it's working great!

**Comment by bentatum** [comment]
@bradabelgit no, it's totally my fault. it's an undocumented behavior. I'm going to keep this open until I'm able to update docs. thanks.

**Comment by bradabelgit** [comment]
Thanks again! Also, would it be possible to pass in the fade-in duration? That would be awesome!

**Comment by bentatum** [comment]
v2.0.0-3

I decided to deprecate `fadeIn`. Since this uses `react-fade`, you can simply pass your `react-fade` params to `fade`.

Setting duration:
```
<ChasingDots fade={{ duration: 3 }} />
```

Removing fade:
```
<ThreeBounce fade={false} />
```

**Comment by bradabelgit** [comment]
@bentatum Perfect, thanks!

**Comment by bentatum** [comment]
I wanted to give everyone a heads up that as of 2.0.0-4, react-fade is no longer a part of this library. If you liked or need the fade effect you can achieve this using a module like [react-fade](https://www.npmjs.com/package/react-fade). Example below:

```js

import { default as React } from 'react'
import { default as Fade } from 'react-fade'
import { Circle } from 'better-react-spinkit'

const Spinner = () =>
  <Fade>
    <Circle />
  </Fade>

export default Spinner

```

Thanks!
