### ISSUE TITLE
React 17 compatibility

### ISSUE THREAD

**Issue by amannn** [bentatum/better-react-spinkit#29]
Can the peer dependency for React also consider v17?

https://github.com/bentatum/better-react-spinkit/blob/bc1ce246bdca01a4f532e57232724ef8710e0b37/package.json#L25

**Comment by chrisgbaker** [comment]
Hello @bentatum! I'm curious if there is anything needed  that I can assist on to move this PR/release forward? While it may not be exhaustive, I've verified through our use cases that this package is compatible with React 17 👍🏻
