### ISSUE TITLE
Delay on show

### ISSUE THREAD

**Issue by dalkir** [bentatum/better-react-spinkit#3]
There is a delay when I show this component, Is there a way to remove this delay?

**Comment by bentatum** [comment]
@dalkir yep, `fadeIn={false}` should do it.

duplicate: https://github.com/bentatum/better-react-spinkit/issues/2

**Comment by dalkir** [comment]
Thank you! Good job in your lib.

**Comment by bentatum** [comment]
@dalkir no problem & thank you. enjoy! 👋
