### ISSUE TITLE
inline-style-prefixer should be a dependency, not devdependency

### ISSUE THREAD

**Issue by jonathan-stone** [bentatum/better-react-spinkit#5]
Getting "missing peer dependency" of inline-style-prefixer in `npm install`, and webpack build fails on an import of inline-style-prefixer. 

Adding inline-style-prefixer as a dependency in my project's package.json fixes the issue, so I assume it should be a dependency in its own project.

Will create a PR if I get a chance.

**Comment by raffihsieh** [comment]
I've created a PR here: https://github.com/bentatum/better-react-spinkit/pull/6

**Comment by bentatum** [comment]
Thanks @raffihsieh
